version: '3.8'

volumes:
  mira-users:

services:

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mira
      - POSTGRES_PASSWORD=pgadmin
    volumes:
      - "mira-users:/var/lib/postgresql/data"

  mira-server:
    build: ./
    restart: always
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/mira
      - SPRING_PROFILES_ACTIVE=dev
    image: 'mira-user-server-oauth'
    depends_on:
      - postgres

  mira-gateway:
    image: mira-gateway
    restart: always
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/mira
      - SPRING_PROFILES_ACTIVE=dev
      - USER_SERVICE_URL=http://mira-server:8080/mira-users/
    ports:
      - 8081:8081
    depends_on:
      - postgres